/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarea1;

import java.awt.Graphics;

/**
 *
 * @author Fiorella Salgado
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDibujo = new javax.swing.JScrollPane();
        panelComandos = new javax.swing.JScrollPane();
        areaComandos = new javax.swing.JTextArea();
        titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelDibujo.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        panelDibujo.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        panelComandos.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        areaComandos.setColumns(20);
        areaComandos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        areaComandos.setRows(5);
        panelComandos.setViewportView(areaComandos);

        titulo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        titulo.setText("Comandos Digitados: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDibujo, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(panelComandos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(panelComandos, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public void dibujar(Figura f) {
        Graphics g = panelDibujo.getGraphics();
        String nombre = f.getNombre();
        if(nombre.equals("Circulo")){
            Circulo.dibujar(g);
        }else if(nombre.equals("Cuadrado")){
            Cuadrado.dibujar(g);
        }else if(nombre.equals("Dona")){
            Dona.dibujar(g);
        }else if(nombre.equals("Ellipse")){
            Ellipse.dibujar(g);
        }else if(nombre.equals("Rectangulo")){
            Rectangulo.dibujar(g);
        }else{
            Triangulo.dibujar(g);
        }
    }
    
    public void agregarComando(String comando){
        if (!comando.isEmpty()) {
            areaComandos.append(String.format("%s%n", comando));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaComandos;
    private javax.swing.JScrollPane panelComandos;
    private javax.swing.JScrollPane panelDibujo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
